---
abstract: 'Synchronous and asynchronous interfaces to This Is My Jam'
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-ThisIsMyJam
recommends:
  AnyEvent: 0
  AnyEvent::HTTP: 0
requires:
  Carp: 0
  HTTP::Tiny: 0
  JSON::Tiny: 0
  Moo: 0
  Try::Tiny: 0
  Type::Utils: 0
  Types::Standard: 0
  URI: 0
  URI::QueryParam: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/sanko/www-thisismyjam
  repository: https://github.com/sanko/www-thisismyjam.git
version: v0.0.3
